name: Playwright Python Tests

on:
  push:
    branches: [ main, development ]

  pull_request:
    branches: [ main ]

jobs:

  test:

    runs-on: window-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Install Playwright Browsers
      run: |
        playwright install --with-deps

    - name: Run Tests
      run: |
        pytest -v --alluredir=reports/allure-results

    - name: Upload Allure Results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: reports/allure-results